defaults:
  interval: 1

latex_thesis_extended:
  file_match: '*.{tex,bib,cls}'
  script:
    - ./bin/build_pdf.sh examples/thesis/hsr/extended
    - evince examples/thesis/hsr/extended.pdf &
latex_thesis_simple:
  file_match: '*.{tex,bib,cls}'
  script:
    - ./bin/build_pdf.sh examples/thesis/hsr/simple
    - evince examples/thesis/hsr/simple.pdf &
latex_article_extended:
  file_match: '*.{tex,bib,cls}'
  script:
    - ./bin/build_pdf.sh examples/article/hsr/extended
    - evince examples/article/hsr/extended.pdf &
